// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ClickOutside: typeof import('./../directives/clickOutside.js')['default']
    Focus: typeof import('./../directives/focus.js')['default']
    IMyIconsAxios: typeof import('~icons/my-icons/axios')['default']
    IMyIconsElement: typeof import('~icons/my-icons/element')['default']
    IMyIconsIconify: typeof import('~icons/my-icons/iconify')['default']
    IMyIconsPinia: typeof import('~icons/my-icons/pinia')['default']
    IMyIconsPnpm: typeof import('~icons/my-icons/pnpm')['default']
    IMyIconsUnocss: typeof import('~icons/my-icons/unocss')['default']
    IMyIconsVite: typeof import('~icons/my-icons/vite')['default']
    IMyIconsVueuse: typeof import('~icons/my-icons/vueuse')['default']
    IMyIconsWindicss: typeof import('~icons/my-icons/windicss')['default']
    InfoText: typeof import('./../components/InfoText.vue')['default']
  }
}

export { }
