// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ClickOutside: typeof import('./../directives/clickOutside.js')['default']
    Focus: typeof import('./../directives/focus.js')['default']
    IconsAxios: typeof import('~icons/icons/axios')['default']
    IconsElement: typeof import('~icons/icons/element')['default']
    IconsPinia: typeof import('~icons/icons/pinia')['default']
    IconsPnpm: typeof import('~icons/icons/pnpm')['default']
    IconsUnocss: typeof import('~icons/icons/unocss')['default']
    IconsVite: typeof import('~icons/icons/vite')['default']
    IconsVueuse: typeof import('~icons/icons/vueuse')['default']
    InfoText: typeof import('./../components/InfoText.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
