// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Focus: typeof import('./../directives/focus.js')['default']
    FullLoading: typeof import('./../components/FullLoading.vue')['default']
    TabSelect: typeof import('./../components/TabSelect.vue')['default']
  }
}

export { }
